package logical

import (
	"bytes"
	"context"
	"fmt"
	"math"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"pgws/internal/control"
	"pgws/internal/privacy"
)

func TestSequenceNextValue(t *testing.T) {
	s := privacy.Sequence{Start: 7, Increment: 5, Min: 1, Max: math.MaxInt64}
	for _, test := range []struct {
		high, want int64
		fail       bool
	}{{0, 7, false}, {-100, 7, false}, {7, 12, false}, {11, 12, false}, {12, 17, false}, {math.MaxInt64 - 1, math.MaxInt64, false}, {math.MaxInt64, 0, true}} {
		next, err := nextSequenceValue(s, test.high)
		if (err != nil) != test.fail || next != test.want {
			t.Fatalf("high=%d next=%d error=%v", test.high, next, err)
		}
	}
	s.Max = 16
	if _, err := nextSequenceValue(s, 12); err == nil {
		t.Fatal("sequence wrapped or exceeded its maximum")
	}
}

func TestLogicalIdentitySequence(t *testing.T) {
	for _, profile := range []string{"identity_default", "identity_always", "serial"} {
		t.Run(profile, func(t *testing.T) { testLogicalSequence(t, profile) })
	}
}

func testLogicalSequence(t *testing.T, profile string) {
	source, replica := logicalFixture(t)
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
	defer cancel()
	column := "bigint GENERATED BY DEFAULT AS IDENTITY (START 7 INCREMENT 5 MINVALUE 1 MAXVALUE 1000)"
	if profile == "identity_always" {
		column = "bigint GENERATED ALWAYS AS IDENTITY (START 7 INCREMENT 5 MINVALUE 1 MAXVALUE 1000)"
	}
	if profile == "serial" {
		column = "bigserial"
	}
	if _, err := source.Exec(ctx, fmt.Sprintf("CREATE TABLE items(id %s PRIMARY KEY,label text NOT NULL UNIQUE)", column)); err != nil {
		t.Fatal(err)
	}
	if profile == "serial" {
		if _, err := source.Exec(ctx, "ALTER SEQUENCE items_id_seq START 7 INCREMENT 5 MINVALUE 1 MAXVALUE 1000 RESTART 7"); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := source.Exec(ctx, `INSERT INTO items OVERRIDING SYSTEM VALUE VALUES(42,'seed'); INSERT INTO items(label) VALUES('source-generated')`); err != nil {
		t.Fatal(err)
	}

	tx, err := source.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	schema, err := ReadCatalog(ctx, tx)
	tx.Rollback(ctx)
	if err != nil || len(schema.Sequences) != 1 {
		t.Fatal("identity discovery", schema.Sequences, err)
	}
	p := privacy.Policy{Version: 1, SchemaHash: privacy.SchemaHash(schema), KeyID: "identity-test"}
	for _, c := range schema.Tables[0].Columns {
		p.Rules = append(p.Rules, privacy.Rule{Table: schema.Tables[0].ID, Column: c.ID, Action: "copy_original"})
	}
	plan, err := privacy.Compile(schema, p, bytes.Repeat([]byte{8}, 32))
	if err != nil {
		t.Fatal(err)
	}
	var system string
	var timeline int64
	if err = source.QueryRow(ctx, `SELECT (pg_control_system()).system_identifier::text,(pg_control_checkpoint()).timeline_id`).Scan(&system, &timeline); err != nil {
		t.Fatal(err)
	}
	target := Target{Pool: replica, Plan: plan, Identity: Identity{Source: control.ID(), Epoch: 1, SystemID: system, Timeline: timeline}}
	if err = target.Initialize(ctx); err != nil {
		t.Fatal(err)
	}
	c := Connector{Source: source.Config().ConnConfig, Target: target}
	slot, publication, _ := c.names()
	t.Cleanup(func() {
		source.Exec(context.Background(), "SELECT pg_drop_replication_slot($1)", slot)
		source.Exec(context.Background(), "DROP PUBLICATION IF EXISTS "+pgx.Identifier{publication}.Sanitize())
	})
	seed, err := c.Seed(ctx)
	if err != nil {
		t.Fatal(err)
	}
	var high int64
	if err = replica.QueryRow(ctx, "SELECT high_water FROM _pgws_ingestion.sequence_watermarks").Scan(&high); err != nil || high != 42 {
		t.Fatal("seed high water", high, err)
	}
	update := "UPDATE items SET id=91 WHERE id=42"
	if profile == "identity_always" {
		update = "UPDATE items SET label='updated' WHERE id=42"
	}
	if _, err = source.Exec(ctx, `BEGIN;INSERT INTO items OVERRIDING SYSTEM VALUE VALUES(501,'temporary');DELETE FROM items WHERE id=501;`+update+`;COMMIT`); err != nil {
		t.Fatal(err)
	}
	run, cancelRun := context.WithCancel(ctx)
	done := make(chan error, 1)
	go func() { done <- c.Run(run) }()
	awaitLogical(t, ctx, func() bool {
		return replica.QueryRow(ctx, "SELECT high_water FROM _pgws_ingestion.sequence_watermarks").Scan(&high) == nil && high == 501
	})
	// Sequence DDL must invalidate the immutable plan even without a later row.
	if _, err = source.Exec(ctx, `ALTER SEQUENCE items_id_seq INCREMENT 6`); err != nil {
		t.Fatal(err)
	}
	select {
	case err = <-done:
		if err == nil {
			t.Fatal("sequence drift did not stop ingestion")
		}
	case <-time.After(8 * time.Second):
		cancelRun()
		t.Fatal("idle sequence drift undetected")
	}
	cancelRun()
	// This is a private standalone copy of the writer, with no source session.
	// The recovery/host publication campaign remains separate from this SQL test.
	if _, err = replica.Exec(ctx, `ALTER TABLE items DROP CONSTRAINT items_label_key`); err != nil {
		t.Fatal(err)
	}
	if _, err = target.PrepareClone(ctx, seed.LSN); err == nil {
		t.Fatal("clone missing approved uniqueness exposed")
	}
	if _, err = replica.Exec(ctx, `ALTER TABLE items ADD UNIQUE(label)`); err != nil {
		t.Fatal(err)
	}
	if _, err = replica.Exec(ctx, `INSERT INTO items VALUES(1000,'exhausted')`); err != nil {
		t.Fatal(err)
	}
	if _, err = target.PrepareClone(ctx, seed.LSN); err == nil {
		t.Fatal("exhausted identity generator exposed")
	}
	var journal bool
	if err = replica.QueryRow(ctx, "SELECT to_regclass('_pgws_ingestion.checkpoint') IS NOT NULL").Scan(&journal); err != nil || !journal {
		t.Fatal("failed detach removed the journal", err)
	}
	if _, err = replica.Exec(ctx, `DELETE FROM items WHERE id=1000`); err != nil {
		t.Fatal(err)
	}
	if _, err = target.PrepareClone(ctx, seed.LSN); err != nil {
		t.Fatal("identity preparation", err)
	}
	var id int64
	if err = replica.QueryRow(ctx, `INSERT INTO items(label) VALUES('branch') RETURNING id`).Scan(&id); err != nil || id != 502 {
		t.Fatal("branch reused deleted ID or lost increment", id, err)
	}
	if err = replica.QueryRow(ctx, `INSERT INTO items(label) VALUES('branch-next') RETURNING id`).Scan(&id); err != nil || id != 507 {
		t.Fatal("branch increment differs", id, err)
	}
	if profile == "identity_always" {
		if _, err = replica.Exec(ctx, `INSERT INTO items VALUES(900,'explicit')`); err == nil {
			t.Fatal("ALWAYS identity semantics lost")
		}
	}
}
