-- RFC-0001 core management schema. Proposed starting contract, not a deployed service.
-- Target PostgreSQL 18. Run only in a new, dedicated management database.
-- All UUIDs are generated by the service. Never import source databases into this schema.
-- Runtime grants, RLS policies, identity-provider tables, and host inventory are deliberately
-- NOT implemented here. Apply least-privilege migrations before production use.
CREATE SCHEMA pgws_control;
REVOKE ALL ON SCHEMA pgws_control FROM PUBLIC;
SET LOCAL search_path = pgws_control, pg_catalog;

CREATE TABLE tenants (
  id uuid PRIMARY KEY,
  name text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE projects (
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, id)
);
CREATE TABLE sources (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  connector text NOT NULL CHECK (connector IN ('physical', 'logical')),
  source_epoch bigint NOT NULL DEFAULT 1 CHECK (source_epoch > 0),
  system_identifier text CHECK (system_identifier ~ '^[0-9]+$'),
  timeline bigint CHECK (timeline > 0),
  endpoint_reference text NOT NULL,
  secret_reference text NOT NULL,
  status text NOT NULL CHECK (status IN (
    'registered','validating','seeding','streaming','blocked','unreachable','disabled')),
  discovery_manifest jsonb NOT NULL DEFAULT '{}',
  observed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, id),
  FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id)
);
CREATE TABLE privacy_policies (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  policy_hash text NOT NULL CHECK (policy_hash ~ '^[0-9a-f]{64}$'),
  policy_document jsonb NOT NULL,
  state text NOT NULL CHECK (state IN ('draft','approved','revoked')),
  approved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, id),
  UNIQUE (tenant_id, project_id, id, policy_hash),
  FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id)
);
CREATE TABLE baselines (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  source_id uuid NOT NULL,
  generation bigint NOT NULL CHECK (generation > 0),
  source_epoch bigint NOT NULL CHECK (source_epoch > 0),
  source_timeline bigint CHECK (source_timeline > 0),
  kind text NOT NULL CHECK (kind IN ('physical_standby','logical_writer')),
  privacy_policy_id uuid,
  privacy_policy_hash text,
  runtime_digest text NOT NULL,
  compatibility_manifest jsonb NOT NULL,
  state text NOT NULL CHECK (state IN ('seeding','catching_up','ready','blocked','retired','failed')),
  observed_applied_source_lsn pg_lsn,
  observed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, id),
  UNIQUE (tenant_id, project_id, source_id, generation),
  FOREIGN KEY (tenant_id, project_id, source_id)
    REFERENCES sources(tenant_id, project_id, id),
  FOREIGN KEY (tenant_id, project_id, privacy_policy_id, privacy_policy_hash)
    REFERENCES privacy_policies(tenant_id, project_id, id, policy_hash),
  CHECK ((privacy_policy_id IS NULL) = (privacy_policy_hash IS NULL)),
  CHECK ((kind = 'logical_writer') = (privacy_policy_id IS NOT NULL)),
  CHECK (kind <> 'physical_standby' OR source_timeline IS NOT NULL)
);
CREATE TABLE snapshots (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  baseline_id uuid NOT NULL,
  source_epoch bigint NOT NULL CHECK (source_epoch > 0),
  source_timeline bigint CHECK (source_timeline > 0),
  requested_source_lsn pg_lsn,
  captured_source_lower_bound pg_lsn,
  policy_hash text,
  storage_name text,
  storage_guid text,
  capture_operation_id uuid,
  state text NOT NULL CHECK (state IN ('pending','held','ready','deleting','deleted','failed')),
  captured_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, id),
  UNIQUE (tenant_id, project_id, storage_guid),
  FOREIGN KEY (tenant_id, project_id, baseline_id)
    REFERENCES baselines(tenant_id, project_id, id),
  CHECK (state <> 'ready' OR (storage_guid IS NOT NULL AND captured_at IS NOT NULL)),
  CHECK (requested_source_lsn IS NULL OR captured_source_lower_bound IS NULL
         OR captured_source_lower_bound >= requested_source_lsn)
);
CREATE TABLE workspaces (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  task_id text NOT NULL,
  desired_state text NOT NULL CHECK (desired_state IN ('running','paused','deleted')),
  phase text NOT NULL,
  desired_revision bigint NOT NULL DEFAULT 1 CHECK (desired_revision > 0),
  next_generation bigint NOT NULL DEFAULT 1 CHECK (next_generation > 0),
  current_generation bigint,
  fencing_token bigint NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
  resource_profile text NOT NULL,
  code_revision text,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, id),
  FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id),
  CHECK (expires_at > created_at)
);

-- Identity checks use IS DISTINCT FROM so NULL raw-policy fields cannot bypass them.
-- These triggers run as the caller. Runtime roles must not own tables or disable triggers.
CREATE FUNCTION check_snapshot_baseline_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pgws_control, pg_catalog AS $$
DECLARE b baselines%ROWTYPE;
BEGIN
  IF TG_OP = 'UPDATE' AND
     ROW(NEW.tenant_id, NEW.project_id, NEW.id, NEW.baseline_id,
         NEW.source_epoch, NEW.source_timeline, NEW.policy_hash)
     IS DISTINCT FROM
     ROW(OLD.tenant_id, OLD.project_id, OLD.id, OLD.baseline_id,
         OLD.source_epoch, OLD.source_timeline, OLD.policy_hash) THEN
    RAISE EXCEPTION 'snapshot identity is immutable' USING ERRCODE = '23514';
  END IF;
  SELECT * INTO b FROM baselines
    WHERE tenant_id = NEW.tenant_id AND project_id = NEW.project_id
      AND id = NEW.baseline_id FOR KEY SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'snapshot baseline does not exist in project' USING ERRCODE = '23503';
  END IF;
  IF ROW(NEW.source_epoch, NEW.source_timeline, NEW.policy_hash)
     IS DISTINCT FROM ROW(b.source_epoch, b.source_timeline, b.privacy_policy_hash) THEN
    RAISE EXCEPTION 'snapshot lineage or policy differs from baseline' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER snapshot_baseline_identity BEFORE INSERT OR UPDATE ON snapshots
  FOR EACH ROW EXECUTE FUNCTION check_snapshot_baseline_identity();

CREATE FUNCTION preserve_baseline_contract() RETURNS trigger
LANGUAGE plpgsql SET search_path = pgws_control, pg_catalog AS $$
BEGIN
  IF ROW(NEW.tenant_id, NEW.project_id, NEW.id, NEW.source_id, NEW.generation,
         NEW.source_epoch, NEW.source_timeline, NEW.kind, NEW.privacy_policy_id,
         NEW.privacy_policy_hash, NEW.runtime_digest, NEW.compatibility_manifest)
     IS DISTINCT FROM
     ROW(OLD.tenant_id, OLD.project_id, OLD.id, OLD.source_id, OLD.generation,
         OLD.source_epoch, OLD.source_timeline, OLD.kind, OLD.privacy_policy_id,
         OLD.privacy_policy_hash, OLD.runtime_digest, OLD.compatibility_manifest) THEN
    RAISE EXCEPTION 'baseline contract is immutable; create a new generation'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER baseline_contract_immutable BEFORE UPDATE ON baselines
  FOR EACH ROW EXECUTE FUNCTION preserve_baseline_contract();

CREATE FUNCTION preserve_policy_document() RETURNS trigger
LANGUAGE plpgsql SET search_path = pgws_control, pg_catalog AS $$
BEGIN
  IF ROW(NEW.tenant_id, NEW.project_id, NEW.id, NEW.version,
         NEW.policy_hash, NEW.policy_document)
     IS DISTINCT FROM
     ROW(OLD.tenant_id, OLD.project_id, OLD.id, OLD.version,
         OLD.policy_hash, OLD.policy_document) THEN
    RAISE EXCEPTION 'policy content is immutable; create a new policy version'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER policy_document_immutable BEFORE UPDATE ON privacy_policies
  FOR EACH ROW EXECUTE FUNCTION preserve_policy_document();
CREATE TABLE workspace_generations (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  generation bigint NOT NULL CHECK (generation > 0),
  snapshot_id uuid NOT NULL,
  phase text NOT NULL,
  cell_reference text,
  volume_name text,
  volume_guid text,
  runtime_reference text,
  runtime_digest text NOT NULL,
  endpoint_metadata jsonb,
  readiness_evidence jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  ready_at timestamptz,
  deleted_at timestamptz,
  PRIMARY KEY (tenant_id, project_id, workspace_id, generation),
  FOREIGN KEY (tenant_id, project_id, workspace_id)
    REFERENCES workspaces(tenant_id, project_id, id),
  FOREIGN KEY (tenant_id, project_id, snapshot_id)
    REFERENCES snapshots(tenant_id, project_id, id),
  CHECK (phase <> 'ready' OR (ready_at IS NOT NULL AND readiness_evidence IS NOT NULL
                             AND endpoint_metadata IS NOT NULL))
);
ALTER TABLE workspaces ADD CONSTRAINT workspace_current_generation_fk
  FOREIGN KEY (tenant_id, project_id, id, current_generation)
  REFERENCES workspace_generations(tenant_id, project_id, workspace_id, generation)
  DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE operations (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  workspace_id uuid,
  kind text NOT NULL,
  expected_generation bigint,
  desired_revision bigint,
  idempotency_scope text NOT NULL,
  idempotency_key text NOT NULL CHECK (length(idempotency_key) BETWEEN 1 AND 200),
  request_hash text NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  status text NOT NULL CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
  current_step text,
  safe_result jsonb,
  safe_error jsonb,
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  lease_owner text,
  lease_until timestamptz,
  fencing_token bigint CHECK (fencing_token >= 0),
  not_before timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (tenant_id, project_id, id),
  UNIQUE (tenant_id, project_id, idempotency_scope, idempotency_key),
  FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id),
  FOREIGN KEY (tenant_id, project_id, workspace_id)
    REFERENCES workspaces(tenant_id, project_id, id)
);
CREATE INDEX operations_runnable ON operations(not_before, created_at)
  WHERE status = 'queued';
CREATE INDEX operations_expired_lease ON operations(lease_until)
  WHERE status = 'running';
CREATE INDEX workspaces_expiring ON workspaces(expires_at)
  WHERE desired_state <> 'deleted';

CREATE TABLE operation_steps (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  operation_id uuid NOT NULL,
  step_name text NOT NULL,
  attempt integer NOT NULL CHECK (attempt > 0),
  fencing_token bigint NOT NULL CHECK (fencing_token > 0),
  state text NOT NULL CHECK (state IN ('started','completed','failed')),
  safe_evidence jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  PRIMARY KEY (tenant_id, project_id, operation_id, step_name, attempt),
  FOREIGN KEY (tenant_id, project_id, operation_id)
    REFERENCES operations(tenant_id, project_id, id)
);
CREATE TABLE snapshot_refs (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  snapshot_id uuid NOT NULL,
  owner_kind text NOT NULL,
  owner_id uuid NOT NULL,
  owner_generation bigint NOT NULL DEFAULT 0 CHECK (owner_generation >= 0),
  hold_tag text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, snapshot_id, owner_kind, owner_id, owner_generation),
  FOREIGN KEY (tenant_id, project_id, snapshot_id)
    REFERENCES snapshots(tenant_id, project_id, id)
);
CREATE TABLE credentials (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  generation bigint NOT NULL,
  role_name text NOT NULL,
  secret_reference text NOT NULL,
  principal_reference text NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, project_id, id),
  FOREIGN KEY (tenant_id, project_id, workspace_id, generation)
    REFERENCES workspace_generations(tenant_id, project_id, workspace_id, generation),
  CHECK (expires_at > created_at)
);
CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  actor_reference text NOT NULL,
  action text NOT NULL,
  target_reference text NOT NULL,
  outcome text NOT NULL,
  operation_id uuid,
  safe_metadata jsonb NOT NULL DEFAULT '{}',
  occurred_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id)
);
CREATE TABLE usage_events (
  tenant_id uuid NOT NULL,
  project_id uuid NOT NULL,
  id uuid NOT NULL,
  resource_reference text NOT NULL,
  metric text NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 0),
  unit text NOT NULL,
  interval_start timestamptz NOT NULL,
  interval_end timestamptz NOT NULL,
  source_event_key text NOT NULL,
  PRIMARY KEY (tenant_id, project_id, id),
  UNIQUE (tenant_id, project_id, source_event_key),
  FOREIGN KEY (tenant_id, project_id) REFERENCES projects(tenant_id, id),
  CHECK (interval_end > interval_start)
);
-- No broad grants are made. The schema is deliberately inaccessible to PUBLIC.
-- Reconciliation, not ON DELETE CASCADE, owns physical resource cleanup.
